theme: jekyll-theme-minimal
title: Product Management Handbook
description: A white label product management handbook for government digital services
logo: https://www.recruited.tech/assets/global/_medium/Scott-Colfer.jpg
baseurl: /product-management-handbook
